[project]
name = "book-repository"
version = "0.1.0"
description = "Handling book seller database operations"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "fastapi>=0.115.12",
    "uvicorn>=0.34.1",
    "pydantic>=2.11.3",
    "pymongo>=4.14.0"
]
